theme: jekyll-theme-minimal
title: Aura official website
description: **Aura - The Future of Decentralized Currency** ğŸŒğŸ’ An innovative blockchain project combining **Proof of Work (PoW) and Proof of Stake (PoS)** to create a secure, scalable, and efficient cryptocurrency. Join the revolution today! ğŸš€